# Portfolio RL Training Notebook (Alpaca + CSV)

Use this notebook to generate the RL portfolio checkpoint. Two options:
1) Fetch daily bars from Alpaca (alpaca-py) for your ticker list (requires ALPACA_API_KEY/ALPACA_API_SECRET env vars).
2) Load a local bulk CSV/Parquet with ~10 years of history (columns: date, ticker, close).

Alpaca data will be saved locally for reuse (CSV + Parquet).
Alpaca paper endpoint: https://paper-api.alpaca.markets/v2

Extra/Optional Tickers:

'QYLD', 'RCL', 'RIVN', 'ROST', 'RTX', 'RUN', 'RYLD', 'SBUX', 'SCHD',
    'SCHW', 'SDY', 'SEDG', 'SHOP', 'SLB', 'SLV', 'SMH', 'SNOW', 'SO', 'SOXX',
    'SPGI', 'SPHD', 'SPLV', 'SPWR', 'SPY', 'SPYD', 'SQ', 'SRE', 'STLA',
    'STT', 'SYK', 'T', 'TEAM', 'TGT', 'TJX', 'TLT', 'TM', 'TMO', 'TROW',
    'TRV', 'TSLA', 'TSM', 'TWLO', 'TXN', 'UAL', 'UBER', 'UNH', 'UNP', 'UPS',
    'USB', 'USMV', 'V', 'VB', 'VEA', 'VLUE', 'VNOM', 'VNQ', 'VO', 'VOO',
    'VTI', 'VTV', 'VUG', 'VWO', 'VYM', 'VZ', 'WBA', 'WMT', 'WORK', 'XEL',
    'XHB', 'XLB', 'XLE', 'XLF', 'XLI', 'XLK', 'XLP', 'XLRE', 'XLU', 'XLV',
    'XLY', 'XME', 'XOM', 'XOP', 'XPEV', 'XRT', 'ZM', 'ZS', 'ZTS', 
    'ADSK', 'ANET', 'APH', 'APTV', 'ASML', 'CDNS', 'CDW', 'CTSH', 'EA', 'EPAM', 'EQIX', 'FICO',
    'FTNT', 'GLW', 'KEYS', 'KLAC', 'LRCX', 'MPWR', 'MSCI', 'ON', 'PAYC', 'PAYX', 'SNPS', 'TEL',
    'TER', 'TTD', 'TTWO', 'WDAY', 'AJG', 'AMP', 'AON', 'CFG', 'CINF', 'COF', 'DFS', 'FITB',
    'GL', 'HBAN', 'ICE', 'IVZ', 'KEY', 'MCO', 'MTB', 'NDAQ', 'PFG', 'RJF', 'WFC', 'ZION',
    'AME', 'AOS', 'CPRT', 'CSX', 'CTAS', 'DOV', 'EFX', 'ETN', 'EXPD', 'FLS', 'GD', 'GEHC',
    'GWW', 'HII', 'ITW', 'J', 'JBHT', 'JCI', 'LHX', 'MAS', 'NOC', 'NSC', 'ODFL', 'PH',
    'PWR', 'ROL', 'ROP', 'SNA', 'TDG', 'TT', 'URI', 'AAP', 'AZO', 'BBY', 'CHD', 'CMA',
    'CPB', 'DPZ', 'DRI', 'HAS', 'HRL', 'KDP', 'KMX', 'LEN', 'LVS', 'MKC', 'MNST', 'ORLY',
    'SJM', 'STZ', 'TSCO', 'VFC', 'WHR', 'YUM', 'YUMC', 'A', 'ALGN', 'BIIB', 'BSX', 'DXCM',
    'HOLX', 'IDXX', 'ILMN', 'INCY', 'IQV', 'LH', 'MRNA', 'MTD', 'REGN', 'RMD', 'STE', 'TFX',
    'VTRS', 'ZBH', 'AEE', 'AES', 'AWK', 'CNP', 'EQR', 'ESS', 'EXR', 'FRT', 'IRM', 'MAA',
    'O', 'PSA', 'SBAC', 'SPG', 'VICI', 'VTR', 'WELL', 'WY', 'APD', 'CE', 'CF', 'DD',
    'DOW', 'ECL', 'EMN', 'FCX', 'MLM', 'MOS', 'NEM', 'NUE', 'PKG', 'PPG', 'SHW', 'VMC',
    'WMB', 'VLO', 'IJR', 'IJH', 'IWB', 'IWR', 'IWN', 'XBI', 'IWF', 'IWD', 'IYT', , 'ADP', 'AEP', 'AFL',
    'AFRM', 'AIG', 'ALL', 'AMD', 'AMGN', 'AMZN', 'ARKF', 'ARKG', 'ARKK',
    'ARKQ', 'ARKW', 'AVGO', 'AXP', 'BA', 'BABA', 'BAC', 'BEN', 'BK', 'BKNG',
    'BLK', 'BLNK', 'BMY', 'BND', 'BYDDF', 'BYDDY', 'C', 'CAT', 'CB', 'CCL',
    'CHPT', 'CHTR', 'CI', 'CL', 'CLX', 'CMCSA', 'COIN', 'COP', 'COST', 'CRM',
    'CRWD', 'CSCO', 'CSIQ', 'CVS', 'CVX', 'D', 'DAL', 'DDOG', 'DE', 'DG',
    'DHR', 'DIA', 'DIS', 'DLTR', 'DOCU', 'DQ', 'DTE', 'DUK', 'DVY', 'ED',
    'EEM', 'EFA', 'EIX', 'EL', 'ENPH', 'EOG', 'ETR', 'EWA', 'EWC', 'EWH',
    'EWJ', 'EWT', 'EWW', 'EWY', 'EWZ', 'EXPE', 'F', 'FDL', 'FDX', 'FE',
    'FSLR', 'FXI', 'GE', 'GILD', 'GIS', 'GLD', 'GM', 'GOOG', 'GOOGL', 'GS',
    'HD', 'HDV', 'HIG', 'HLT', 'HMC', 'HON', 'HOOD', 'HSY', 'HUM', 'HYG',
    'IBM', 'IEMG', 'INDA', 'INTC', 'INTU', 'ISRG', 'IWM', 'IYR', 'JBLU',
    'JD', 'JEPI', 'JEPQ', 'JNJ', 'JPM', 'K', 'KHC', 'KMB', 'KMI', 'KO', 'KR',
    'KWEB', 'L', 'LCID', 'LI', 'LIN', 'LLY', 'LMT', 'LOW', 'LQD', 'LUV',
    'LYFT', 'MA', 'MAR', 'MCD', 'MCHI', 'MDB', 'MDLZ', 'MDT', 'MELI', 'MET',
    'META', 'MMC', 'MO', 'MPC', 'MRK', 'MS', 'MSFT', 'MTUM', 'MU', 'NCLH',
    'NEE', 'NET', 'NFLX', 'NIO', 'NKE', 'NOBL', 'NOW', 'NU', 'NVDA', 'OKTA',
    'ORCL', 'OXY', 'PCG', 'PDD', 'PEG', 'PEP', 'PFE', 'PG', 'PGR', 'PLD',
    'PLTR', 'PNC', 'PPL', 'PRU', 'PSX', 'PYPL', 'QCOM', 'QQQ', 'QS', 'QUAL'

In [1]:
import torch
print(torch.__version__, "cuda avail:", torch.cuda.is_available())

2.9.1+cu130 cuda avail: True

In [2]:
import os
import sys, pathlib
import pandas as pd
from core.alpaca_data import fetch_intraday_bars
from core.portfolio_rl import (
    format_price_frame,
    optimize_portfolio,
    optimize_portfolio_inference,
)

ALPACA_API_KEY = 'PKFCKZ2H4EOJFXEUGIRLQSB5ML'

os.environ['ALPACA_API_KEY'] = ALPACA_API_KEY
ALPACA_API_SECRET = '7TQibrHnTNQZHSnTUKiJRGjSuKDcCj6qdt9RDzjvBp34'

os.environ['ALPACA_API_SECRET'] = ALPACA_API_SECRET
root = pathlib.Path().resolve()
sys.path.append(str(root))

# --- Toggle data source ---
USE_ALPACA = True  # set False to use local CSV

# Alpaca settings
ALPACA_TICKERS = [
    'AAL', 'AAPL', 'ABBV', 'ABNB', 'ABT', 'ACN', 'ADBE'
]


ALPACA_START = pd.Timestamp.today() - pd.DateOffset(years=1)
ALPACA_END = pd.Timestamp.today()
ALPACA_OUT = root / 'data' / 'bulk_prices' / 'alpaca_daily2.parquet'
# Local CSV fallback
DATA_FILE = root / 'data' / 'bulk_prices' / 'ten_year_prices2.csv'
DATE_COL = 'Date'
PRICE_COL = 'Close'
TICKER_COL = 'Ticker'

# Training hyperparameters
horizon = 30
top_k = 10
episodes = 100  # expect long runtime
lr = 1e-5
risk_aversion = 0.01
CHECKPOINT_PATH = root / 'models' / 'portfolio_policy.pt'

print('Checkpoint will be saved to', CHECKPOINT_PATH)
print('Using Alpaca:', USE_ALPACA)

Checkpoint will be saved to C:\Utah-State-University\DATA6630\finalproject\models\portfolio_policy.pt
Using Alpaca: True

In [3]:
if USE_ALPACA:
    if ALPACA_OUT.exists():
        print('Loading cached Alpaca data from', ALPACA_OUT)
        prices_raw = pd.read_parquet(ALPACA_OUT)
    elif ALPACA_OUT.with_suffix('.csv').exists():
        print('Loading cached Alpaca data from', ALPACA_OUT.with_suffix('.csv'))
        prices_raw = pd.read_csv(ALPACA_OUT.with_suffix('.csv'))
    else:
        print('Fetching intradaily bars from Alpaca...')
        daily = fetch_intraday_bars(ALPACA_TICKERS, start=ALPACA_START, end=ALPACA_END)
        if daily.empty:
            raise RuntimeError('Alpaca returned no data; check credentials, tickers, or date range.')
        ALPACA_OUT.parent.mkdir(parents=True, exist_ok=True)
        daily.to_parquet(ALPACA_OUT, index=False)
        daily.to_csv(ALPACA_OUT.with_suffix('.csv'), index=False)
        prices_raw = daily
else:
    print('Loading local CSV...', DATA_FILE)
    prices_raw = pd.read_csv(DATA_FILE)

# Normalize column names regardless of source
rename_map = {}
cols = {c.lower(): c for c in prices_raw.columns}
if 'symbol' in cols and 'ticker' not in prices_raw.columns: rename_map[cols['symbol']] = TICKER_COL
if 'timestamp' in cols and DATE_COL not in prices_raw.columns: rename_map[cols['timestamp']] = DATE_COL
if 'ds' in cols and DATE_COL not in prices_raw.columns: rename_map[cols['ds']] = DATE_COL
if 'close' in cols and PRICE_COL not in prices_raw.columns: rename_map[cols['close']] = PRICE_COL
prices_raw = prices_raw.rename(columns=rename_map)

prices = format_price_frame(
    prices_raw,
    date_col=DATE_COL,
    price_col=PRICE_COL,
    ticker_col=TICKER_COL,
)
print(f"Loaded {len(prices)} rows covering {prices['ticker'].nunique()} tickers.")
print('Date coverage:', prices['ds'].min(), '->', prices['ds'].max())
prices.head()

Fetching intradaily bars from Alpaca...
Loaded 854731 rows covering 7 tickers.
Date coverage: 2024-12-04 09:00:00+00:00 -> 2025-12-04 00:59:00+00:00

                         ds ticker  close
0 2024-12-04 09:10:00+00:00    AAL  14.53
1 2024-12-04 09:27:00+00:00    AAL  14.53
2 2024-12-04 11:19:00+00:00    AAL  14.50
3 2024-12-04 12:00:00+00:00    AAL  14.54
4 2024-12-04 12:02:00+00:00    AAL  14.58

## Train RL for 10min horizon (h=10 minutes)

In [3]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 10
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
print(result['portfolio'].head())

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 93.947% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.339% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 87.45% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 84.861% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.183% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.236% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 85.138% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 92.066% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 90.008% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 94.826% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.052% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 91.888% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 93.327% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.799% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.152% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.416% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.742% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 83.386% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 87.473% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.374% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 91.394% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

   asset    weight  expected_return
0     DG  0.089923         0.142840
1   JEPQ  0.100138         0.134529
2  GOOGL  0.089412         0.133962
3   BLNK  0.104213         0.131885
4   IEMG  0.109627         0.126528

In [4]:
inference = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
inference['portfolio']

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 93.947% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.339% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 87.45% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 84.861% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.183% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.236% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 85.138% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 92.066% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 90.008% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 94.826% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.052% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 91.888% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 93.327% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.799% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 89.152% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 98.416% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.742% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 83.386% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 87.473% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 88.374% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency 10T corresponds to 91.394% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency 10T
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.

   asset    weight  expected_return
0     DG  0.089952        -0.062079
1   JEPQ  0.100146        -0.054872
2  GOOGL  0.089415        -0.026653
3   BLNK  0.104246        -0.024655
4   IEMG  0.109582         0.048739
5     MO  0.102601         0.091173
6   ARKQ  0.095728        -0.115710
7    DVY  0.107690        -0.012031
8    EOG  0.102537        -0.010575
9     KO  0.098102         0.003411

## Train RL for 1h horizon (h=60 minutes)

In [5]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 60
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
print(result['portfolio'].head())

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.409% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.589% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 86.226% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.714% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.141% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 87.669% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.396% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.928% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.844% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 92.144% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.784% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.319% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.492% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.611% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 87.528% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 92.804% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 82.881% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.622% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)


  asset    weight  expected_return
0  CHTR  0.107288         0.164958
1   EWH  0.096021         0.154429
2   MPC  0.089612         0.151368
3   EIX  0.101602         0.148291
4   GIS  0.106257         0.144047

In [6]:
inference = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
inference['portfolio']

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.409% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.589% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 86.226% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.714% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.141% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 87.669% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.396% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.928% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.844% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 92.144% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.784% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.319% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 84.492% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 93.706% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.611% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 87.528% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 92.804% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 82.881% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency H corresponds to 83.622% of the data.
WARNING - (NP.df_utils._infer_frequency) - Defined frequency D is different than major frequency H
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)


  asset    weight  expected_return
0  CHTR  0.107233         0.000342
1   EWH  0.095991         0.001398
2   MPC  0.089507        -0.084332
3   EIX  0.101626         0.066766
4   GIS  0.106295         0.038688
5   KMB  0.091905         0.024642
6    GS  0.098009        -0.079185
7   FDL  0.111867        -0.112874
8   EWZ  0.105585         0.078614
9  MTUM  0.091982        -0.025014

## Train RL for 1d horizon (h=1440 minutes)

In [7]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 1440
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
print(result['portfolio'].head())

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.969% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.395% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.488% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.2% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.395% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.2% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.444% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.161% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.105% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.4% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.582% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.8% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 93.701% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 93.13% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 91.698% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.024% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.547% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.

  asset    weight  expected_return
0  EXPE  0.105966         0.185059
1   MDB  0.106038         0.163252
2   PRU  0.096903         0.138702
3   ACN  0.103651         0.130790
4   ETR  0.102703         0.127298

In [8]:
inference = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
)
inference['portfolio']

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.969% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.395% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.488% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.2% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.395% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.2% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.444% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.161% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 92.105% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.4% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.582% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.8% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 93.701% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 93.13% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 91.698% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 94.024% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency B corresponds to 95.547% of the data.
INFO - (NP.df_utils._infer_frequency) - Defined frequency is equal to major frequency - D
INFO - (NP.config.init_data_params) - Setting normalization to global as only one dataframe provided for training.
WARNING - (py.warnings._showwarnmsg) - c:\Utah-State-University\DATA6630\finalproject\core\portfolio_rl.py:419: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_val = pd.concat([sf_fcst_val, lstm_val_df, pycaret_val_df, np_val_df, s5_val_df], ignore_index=True)

WARNING - (NP.forecaster.fit) - When Global modeling with local normalization, metrics are displayed in normalized scale.
INFO - (NP.df_utils._infer_frequency) - Major frequency D corresponds to 79.775% of the data.

  asset    weight  expected_return
0  EXPE  0.105936         0.131148
1   MDB  0.106048        -0.131688
2   PRU  0.096902         0.132145
3   ACN  0.103642        -0.011270
4   ETR  0.102617        -0.053133
5   AEP  0.096720        -0.088539
6  GILD  0.090156        -0.037423
7    EL  0.103883        -0.085856
8   HMC  0.095668         0.005812
9    BK  0.098428         0.044436

###GraphEnv Portfolio Optimizer

In [3]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 10
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result_graph = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m_graph.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
print('Top portfolios (graph):')
print(result_graph.get('top_portfolios'))

OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "c:\Users\seths\.conda\envs\forecastapp\Lib\site-packages\torch\lib\c10.dll" or one of its dependencies.

In [ ]:
inference_graph = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_10m_graph.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
inference_graph['portfolio']

In [ ]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 60
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result_graph = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m_graph.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
print('Top portfolios (graph):')
print(result_graph.get('top_portfolios'))

In [ ]:
inference_graph = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_60m_graph.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
inference_graph['portfolio']

In [ ]:
import gc, torch
try:
    torch.cuda.empty_cache()
except Exception:
    pass
gc.collect()
HORIZON_MINUTES = 1440
RESAMPLE_RULE = f"{HORIZON_MINUTES}min"
HORIZON_STEPS = 1
result_graph = optimize_portfolio(
    prices=prices,
    horizon=HORIZON_STEPS,
    top_k=top_k,
    episodes=episodes,
    lr=lr,
    risk_aversion=risk_aversion,
    checkpoint_path=CHECKPOINT_PATH.with_name(f'portfolio_policy_{HORIZON_MINUTES}m_graph.pt'),
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
print('Top portfolios (graph):')
print(result_graph.get('top_portfolios'))

In [ ]:
inference_graph = optimize_portfolio_inference(
    prices=prices,
    checkpoint_path=str(CHECKPOINT_PATH.with_name(f'portfolio_policy_1440m_graph.pt')),
    horizon=HORIZON_STEPS,
    risk_aversion=risk_aversion,
    resample_rule=RESAMPLE_RULE,
    device='cuda',
    rl_mode='graph',
)
inference_graph['portfolio']